### ISSUE TITLE
demo/index.html: multiple searches lead to different behavior between inm7 docs and demo example

### ISSUE THREAD

**Issue by TobiasKadelka** [psyinfra/tipue-search-lite#1]
demo/index.html does not reset the timer when searching two times in a row the same word.

This leads to the timer displaying search times like 1610.32 seconds.

**Comment by aqw** [comment]
Yeah; that was an improvement I made to this fork (specifically e2128bec544bf4fec45d4e68f353568f8bee1d54) that I havn't ported back to the INM-7 docs yet.

Is there an issue with the version specifically in this repo? Otherwise, I recommend closing this issue and (if needed) opening a request in the INM-7 docs repo to refresh the TSL code.

**Comment by aqw** [comment]
Thanks for updating the description. The bug is more clear now. Indeed, this should be fixed. Thanks for identifying it!
